spring:
  application:
    name: blackjack
  datasource:
    url: jdbc:mysql://localhost:3306/blackjack?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zingo
    password:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

handlebars:
  suffix: .html
  cache: false # 배포시에는 true로
  expose-session-attributes: true # 핸들바에서 세션데이터를 인식한다